language: c
env:
  global:
    - BLASFEO_TARGET=X64_AUTOMATIC
    - HPIPM_TARGET=AVX
    - ACADOS_UNIT_TESTS="ON"
    - ACADOS_EXAMPLES="ON"
    - ACADOS_WITH_QPOASES="ON"
    - ACADOS_LINT="OFF"
    - TEMPLATE_MATLAB="OFF"
    - ACADOS_MATLAB="OFF"
    - ACADOS_OCTAVE="OFF"
    - ACADOS_PYTHON="OFF"
    - ACADOS_ON_TRAVIS="ON"
    - ACADOS_DOCS="OFF"

os: linux
sudo: required
dist: xenial

group: travis_latest

services:
  - xvfb

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
      - deadsnakes

matrix:
  include:
    - name: MacOS Build
      os: osx
      osx_image: xcode9.4
      # osx_image: xcode10.1
      env:
        - DEPLOY_NAME="osx-python"

    - name: Linux Gcc6 - Octave interface
      env:
        - DEPLOY_NAME="linux octave gcc6"
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - ACADOS_OCTAVE="ON"
        - ACADOS_EXAMPLES="OFF"
        - ACADOS_UNIT_TESTS="OFF"

    - name: Linux Gcc6 - Python interface + docs
      env:
        - DEPLOY_NAME="linux python gcc6"
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - ACADOS_PYTHON="ON"
        - ACADOS_DOCS="ON"
        - ACADOS_EXAMPLES="OFF"
        - ACADOS_UNIT_TESTS="OFF"

    - name: Linux Gcc4.9 - Octave interface + coverage
      env:
        - DEPLOY_NAME="linux-octave-coverage-gcc49"
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
        - COVERAGE="lcov"
        - ACADOS_OCTAVE="ON"

    - name: Linux Clang
      env:
        - DEPLOY_NAME="linux-python-clang37"
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"
        - ACADOS_OCTAVE="OFF"
        - ACADOS_UNIT_TESTS="ON"
        # - ACADOS_EXAMPLES="OFF"
    # - name: Linux Gcc5
    #   env:
    #     - DEPLOY_NAME="linux-python-gcc5"
    #     - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

cache:
  ccache: true
  directories:

before_install:
  - eval "${MATRIX_EVAL}"
  - SECTION='before_install'
  - export SCRIPT_DIR="${TRAVIS_BUILD_DIR}/ci/${TRAVIS_OS_NAME}"
  - export SHARED_SCRIPT_DIR="${TRAVIS_BUILD_DIR}/ci/shared"
  - source "${SCRIPT_DIR}/dispatch.sh"

install:
  - SECTION='install'
  - source "${SCRIPT_DIR}/dispatch.sh"

script:
  - SECTION='script'
  - source "${SCRIPT_DIR}/dispatch.sh"

after_success:
  - SECTION='after_success'
  # - mkdir -p "${DEPLOY_FOLDER}"
  - source "${SCRIPT_DIR}/dispatch.sh"

before_deploy:
  - cd "${ACADOS_INSTALL_DIR}/lib/"
  - tar -zcf acados-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz *
  - cd ../..
   
deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file_glob: true
  file: "${ACADOS_INSTALL_DIR}/lib/acados-*"
  skip_cleanup: true
  on:
    tags: true
